name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Select Xcode 16.1
      run: sudo xcode-select -s /Applications/Xcode_16.1.app
    - name: Build, test, and code coverage
      run: make
